### ISSUE TITLE
Missing Part

### ISSUE THREAD

**Issue by e7110** [m1lw0rm/cybershark.rs-leaked#3]
config.php still missing

**Comment by m1lw0rm** [comment]
`<?php
$config['site']['type'] = "Your Site Name";

// Debug mod za SQL
// 0 - off
// 1 - ne reportuje greske (sporije, uvek pokusava da se konektuje ako ne radi)
// 2 - ne pokusava konekciju (sql off)
$config['sql']['debug'] = 0;

// WebFTP editable files
$config['gpanel']['editable'] = array("cfg","ini","txt","res","log","yml","properties","ban");

if ( $config['site']['type'] == "PutinStresser.eu" ) {
    // Podesavanje baze
    $config['sql']['host'] = "localhost";
    $config['sql']['user'] = "user";
    $config['sql']['pass'] = "pw";
    $config['sql']['db'] = "db";
    $config['sql']['port'] = "3306";

    // Online/offline ceo sajt + razlog
    $config['site']['offline'] = 0;
    $config['site']['offlineReason'] = "Game Panel je privremeno offline zbog planiranog odrzavanja. Vise informacija na www.cybershark.rs | www.gather.rs | www.facebook.com/cybershark.rs";
    $config['site']['offlinePassword'] = "0ffl1n3";

    // PayPal email nalog na koji idu uplate
    $config['paypal']['email'] = "urosh93@hotmail.com";
    
    // Podesavanje kontakt forme
    $config['contact']['email'] = "admin@cybershark.rs";
    $config['contact']['name'] = "Cyber Shark Hosting";
    $config['contact']['subject'] = "Poruka sa kontakt forme";

    // noreply mail
    $config['noreply']['name'] = "Cyber Shark Hosting";
    $config['noreply']['email'] = "noreply@cybershark.rs";

    // Languages
    $config['site']['languages'] = array("serbian", "english", "cirilica");
    $config['site']['defaultLanguage'] = "serbian";


    // Demo korisnici (nemaju nikakve privilegije)
    $config['site']['demoUsers'] = array("2809", "40450");

    // eMS checkout
    //$config['ems']['storeID'] = "65";
    //$config['ems']['storeID'] = "53";
   // $config['ems']['storeName'] = "Cyber Shark Hosting";
    //$config['ems']['shopKey'] = 'kP{46rH/t$2JRj&3g8M-5%yFwQ!79xA=sC}9*5Kpd+4B7S_c?8bZzN6$X?f32Y-qo7T&2+nGD9!ia%E63Lm=}e8Wt5A/_g4FpJ{5';
    //$config['ems']['shopKey'] = 'g*6K8D-jL/q3xP7=5b!NG2f?i&4S%9By7e$ZM9d}8n_HoW3{6t+YpR2!4_Tw=r5EsJ}4&c2Fa3Q*{m5X9-Czk7?A$qE68W/aP%t5';
    //$config['ems']['development'] = 0;

    // Site specific
    $config['site']['name'] = "Cyber Shark Hosting";
    $config['site']['adminContact'] = "admin@cybershark.rs";
    $config['site']['shortname'] = "CyberShark";
    $config['site']['freeForumDomain'] = 'vasdomen.m5x.org';
    $config['site']['url'] = "http://www.cybershark.rs";
    $config['site']['adminUrl'] = "http://ur0s.com";
    $config['site']['version'] = "v2.0";
    $config['site']['facebookpage'] = "http://www.facebook.com/cybershark.rs";
    $config['site']['clientsSubdomain'] = "www.m5x.org";

} else {
    ob_clean();
    die("Error! Invalid site type \"{$config['site']['type']}\"!");
}

?>
`

**Comment by e7110** [comment]
Hvl ti

Datuma sri, 21. stu 2018. 00:07 Mr.Milw0rm <notifications@github.com piše:
